"""empty message

Revision ID: e1c72c43f372
Revises: 404a2745197b
Create Date: 2019-11-25 14:02:17.604006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c72c43f372'
down_revision = '404a2745197b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'order_id')
    # ### end Alembic commands ###
